# Generated by Django 5.0.4 on 2024-04-12 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAyuda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ayuda', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivosUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_archivo', models.URLField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialServicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_servicio', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='MesaDeAyuda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('tipo_ayuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoayuda')),
            ],
        ),
    ]
