# Generated by Django 5.0.3 on 2024-04-13 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_historialservicios_archivo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosusuario',
            name='nombre_archivo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivosusuario',
            name='tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.servicio'),
            preserve_default=False,
        ),
    ]
